### ISSUE TITLE
Transpiling to ES5

### ISSUE THREAD

**Issue by ussuritiger** [sindresorhus/slugify#50] opened 2020-05-12 11:36 UTC
First of all thanks for the great package. I am wondering whether it is possible to transpile the package into ES5 so it can be used in older browsers as well. For example, if the package is used in IE11 the arrow function is not supported and therefore results in an error. Edge 18 does not support spread syntax so also results in an error.

Of course the app that uses the package can transpile the package itself but that feels more like an overhead. Compiling the package to ES5 in the first place should not bring any problems on the other hand.

**Comment by sindresorhus** [comment] 2020-05-12 11:50
Duplicate of #32

**Closed** 2020-05-12 11:50 UTC
